# Generated by Django 5.2.2 on 2026-02-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='dialing_code',
        ),
    ]
