# Generated by Django 5.2.2 on 2026-02-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0002_remove_country_dialing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dialing_code',
            field=models.CharField(default='+91', max_length=10),
            preserve_default=False,
        ),
    ]
