# Generated by Django 5.2.2 on 2026-02-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0003_country_dialing_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='dialing_code',
        ),
    ]
