# Generated by Django 5.2.2 on 2026-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
