# Generated by Django 5.2.2 on 2026-02-21 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0003_country_dialing_code'),
        ('User', '0002_registrationrequest_is_email_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=-1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=100)),
                ('subscription_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('employee_count', models.PositiveIntegerField()),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('demo_status', models.CharField(choices=[('IN_PROGRESS', 'In_Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('nature_of_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Meta.natureofbusiness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
